import type { Metadata } from "next";
import { Assistant } from "next/font/google";

const assistant = Assistant({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "React Web Radio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={assistant.className}>
        <div className="app-wrap">
          <main className="player-wrap" style={{ opacity: 1 }}>
            <figure className="player-bg" />
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
